export const metadata = {
    title: "Date Time Calculator | Privacy Policy",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <>{children};</>;
}
